### ISSUE TITLE
Regex clears upon Input drag

### ISSUE THREAD

**Issue by CatRabbit499** [ao5357/development_favicon#10]
If you accidently drag a regex row by its `<Input>` box and it happens to be released over another regex row's `<Input>` box, both `<Input>` boxes are erased and can't be recovered with any amount of <kbd>Ctrl</kbd>+<kbd>Z</kbd>

Google Chrome | 70.0.3538.77 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
JavaScript | V8 7.0.276.32
Flash | 31.0.0.122

**Comment by ao5357** [comment]
@CatRabbit499 ,

Thank you for the detailed error report! I will keep you up to date on the repair here on this thread.

And thank you for your interest in development_favicon,
bpcz
