### ISSUE TITLE
Gmail unread favicon support?

### ISSUE THREAD

**Issue by orschiro** [ao5357/development_favicon#12]
Hi guys,

I am wondering if we can make dev favicon compatible with the Gmail unread favicon feature?

Currently dev favicon setting is not showing on the favicon if Gmail unread favicon is enabled.

![image](https://user-images.githubusercontent.com/170947/77517302-2d1b8600-6e7c-11ea-8688-217bfdebf6a8.png)

![image](https://user-images.githubusercontent.com/170947/77517337-3efd2900-6e7c-11ea-85f9-536bae61a5de.png)

![image](https://user-images.githubusercontent.com/170947/77517364-48869100-6e7c-11ea-8c1e-3179cbc81373.png)

**Comment by ao5357** [comment]
@orschiro 

Can you confirm that the pattern matches (ie. that there's a green top stripe)?

If so, does the green stripe disappear when the unread count changes? Does it come back when you reload the page? What about if you open gmail in a new tab?

Thanks!,
bpcz

**Comment by orschiro** [comment]
Good catch! Sadly neither working in a new tab without the unread feature.

Anyone else?

![image](https://user-images.githubusercontent.com/170947/77550268-36731580-6eb1-11ea-8285-dbab92d42169.png)

![image](https://user-images.githubusercontent.com/170947/77550284-3d018d00-6eb1-11ea-959e-c3cfb949befc.png)

**Comment by ao5357** [comment]
@orschiro Closing out this ticket as a 'wontfix', sorry.

I tested with a different pattern: `.*?mail\.google\.com\/mail\/u\/0.*`
...which theoretically would work, though it seems gmail updates its favicon after the extension does, updates it fully, and is more aggressive about it.

This extension focuses on being fast and privacy-conscious, and updating the extension to override user settings on gmail would require breaking the stated goals of the project.

**Comment by orschiro** [comment]
I understand, thank you!
