### ISSUE TITLE
Extension no longer in Chrome Webstore? (2023)

### ISSUE THREAD

**Issue by patrickhunt** [ao5357/development_favicon#15]
The webstore URL now 404s and the extension no longer appears in search results :(
Both of these urls don't work:
 * https://chrome.google.com/webstore/detail/development-favicon/mopggoekgknbopeodgiodphdofgeojkb
 * https://chrome.google.com/webstore/detail/pdfbbnojibegcfdmhcccicmllbbkpeaf (Note: this is probably old and supposed to fail)

Also, the "Extension options" link no longer does anything. (On my system) this link is found at:
chrome://extensions/?id=pdfbbnojibegcfdmhcccicmllbbkpeaf

I am willing to try and fix it myself, as a contributor, (but it looks like this might be admin stuff that only the owner can do).

**Comment by ao5357** [comment]
@patrickhunt Yeah, Google emailed on June 1st with the following:

![image](https://github.com/ao5357/development_favicon/assets/497987/c71c08cc-d43f-4e07-94ad-5089ee2fb880)

I haven't had the opportunity to even look at it, much less do anything to rectify the situation. With all the uncertainty about manifest versions and the webstore pulling stuff like this somewhat-frequently, I'm not super certain I want to manage a Chrome extension anymore.

Would you be interested in cloning the repo down, zipping it up, and submitting it for a new listing to the web store? If so, I'd be happy to update readmes, blog posts, etc. to reflect the new store URL. If not, no worries, but it might be quite a delay before there's an official version back in the store. Of course, you're always welcome to put your `chrome://extensions` in Developer mode and then sideload an unpacked version.

Thank you, as always, for your interest in development_favicon!

**Comment by patrickhunt** [comment]
Yeah, I'd be interested in helping. For the record, I don't know anything about developing Chrome extensions, but I'm sure I could figure it out.
Sorry if this is a dumb question, but if I cloned and re-submitted, wouldn't it create a "new" extension and orphan all the current installations?  Should I be added to the existing extension instead?

**Comment by ao5357** [comment]
You're right, @patrickhunt , for logistical reasons I should keep managing the extension if it's possible.

I re-submitted the existing extension in the hopes they would reconsider. They did not.

When I get a chance, I will remove the activeTab permission from the manifest, do some quick tests, then roll a release with just that little change and re-submit. If that version gets rejected, I will officially close out the official version in the Chrome Web Store.

**Comment by ao5357** [comment]
@patrickhunt I have resubmitted the extension for review, this time without the activeTab permission in the manifest. I will update here if the Chrome web store accepts it now. If the extension is approved and re-listed, it will be the https://chrome.google.com/webstore/detail/development-favicon/mopggoekgknbopeodgiodphdofgeojkb address

**Comment by ao5357** [comment]
It seems https://chrome.google.com/webstore/detail/development-favicon/mopggoekgknbopeodgiodphdofgeojkb is back up and running, so I will close the tab on this closed ticket. Thank you for your continued interest in development_favicon!
