### ISSUE TITLE
Any way to support page titles as well as url?

### ISSUE THREAD

**Issue by CyrusDG** [ao5357/development_favicon#2]
I've found your solution to be the best out there but the way Google differentiates URLs for different Google accounts is very frustrating.  They use an integer that is based on the order that the user logged in to that account.

e.g., https://mail.google.com/mail/u/0/#inbox, https://mail.google.com/mail/u/1/#inbox, https://mail.google.com/mail/u/2/#inbox

And each time you reload chrome, the order of course can change so the favicon colours do not match up with the right account. 

Any suggestions on how to solve this? One option I thought was to allow the page title to be used as a criteria instead of the target URL. 

Thanks again for your hard work

**Comment by ao5357** [comment]
I'm presently bogged down, but can take a look at what such a solution would take -- perhaps in a couple weeks.

If you have the JavaScript chops, I'll happily accept a clean PR.

**Comment by davmillar** [comment]
Turns out it wasn't terribly difficult! I've made a PR, please have a look and let me know if it needs any revisions. Happy #Hacktoberfest!

**Comment by ao5357** [comment]
DUDE!

I'll merge right now, and then deploy to the store at my nearest possible convenience.

This is so cool! Thank you very much.
