### ISSUE TITLE
Dropping a pattern on other pattern's child nodes

### ISSUE THREAD

**Issue by Glutnix** [ao5357/development_favicon#3]
Drag a pattern block onto another pattern block without dropping it. 

Hover over different elements and watch the dashed border appear around the child elements of that pattern block. It should not do this.

Drop it on a label or field if you like unexpected behaviour :)

**Comment by ao5357** [comment]
Sorry for the delay on getting back to you about this. I will investigate this issue when I have a free moment. If you'd like to tackle it and PR, I'd be grateful.
