### ISSUE TITLE
Won't seem to match correctly on URLs with port numbers.

### ISSUE THREAD

**Issue by davmillar** [ao5357/development_favicon#5]
Tried using the following regex:
.*\-devnet\.ourenvironment\.info.*
Regex Pal thinks it should handle my URL fine, but it doesn't:
https://jsmith-devnet.ourenvironment.info:8001/dev/#!profile

Will investigate the issue later myself when not at the day job, unless someone else has time before I do.

**Comment by davmillar** [comment]
Never mind, was a glitch on my end. Everything is fine. :)

**Comment by ao5357** [comment]
David,

Thanks for your interest in development_favicon!

Regards,
bpcz
