### ISSUE TITLE
make Regex Pattern input wider

### ISSUE THREAD

**Issue by ispringer** [ao5357/development_favicon#8]
Can you please make the regex pattern input wider, so the full regex can be seen without having to select it and paste it into a text editor? Maybe like 300px or 400px.

**Comment by ao5357** [comment]
That's a good idea! I'll try to find some time to tackle it soon.

**Comment by ao5357** [comment]
@ispringer I may have went a little overboard in fulfilling your request. Please review the changes as deployed.

Thank you for your interest in development_favicon!

**Comment by ispringer** [comment]
Wow, looks awesome! Thanks!

By the way, out of curiosity, why do slashes need to be escaped in the regular expressions? They are normally not a special character except within regular expression literals.

**Comment by ao5357** [comment]
You make a good point. I just tested an unescaped slash and it worked just fine. While I'd entertain changing the documentation via a new issue, I don't think recommending the escape of slashes is necessarily bad advice; it encourages consistency between constructed expressions and literals.

Have a great Monday!
