### ISSUE TITLE
Doesn't work in Chrome 69

### ISSUE THREAD

**Issue by jgbishop** [ao5357/development_favicon#9]
The default favicon for local files is really hard to see in Chrome 69, so I installed this extension to try and fix that problem. From what I can tell, the extension doesn't do anything for local file-based URLs (e.g. `file:///C:/Some/Folder/some-file.html`)

I tried the following regex for local files: `file:\/\/\/.*`, as well as `file:.*`, but neither did anything. Keying off of the page title also has no effect.

I can get it to work with http-style URLs.

**Comment by ao5357** [comment]
@jgbishop Thank you for your interest in development_favicon!

I just did a quick test in Chrome 70, and think I found the solution: from chrome://extensions/ click on the "Details" button for the extension (the same one where you now go to get to the extension settings):
![screenshot from 2018-09-05 15-08-04](https://user-images.githubusercontent.com/497987/45115339-92cee280-b11d-11e8-9978-f981f34dbc40.png)

From that pane, toggle the switch for "Allow access to file URLs":
![screenshot from 2018-09-05 15-08-16](https://user-images.githubusercontent.com/497987/45115373-aa0dd000-b11d-11e8-847c-34dea2685fd4.png)

...and you should be home free!

Hope this helps,
bpcz

**Comment by jgbishop** [comment]
I wasn't aware of that setting! It does indeed change things, but now I notice another problem:

Once a favicon is set for a local file, there doesn't appear to be a way to update it (the browser appears to aggressively cache it). I was playing around with the colors, and now one of my local files has a white box icon, with no apparent way to clear it.

Do you know of any way to force the browser to clear the local favicon cache?

**Comment by ao5357** [comment]
On that front my hands are largely tied -- the web at large may be of more assistance, but in my experience the favicon cache is pretty persistent.
